pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                // Add your build steps here
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                // Add your test steps here
            }
        }
    }
    
    post {
        always {
            echo 'Hello World!'
            // Add any post-build actions here
        }
    }
    
    triggers {
        githubPush()
    }
}
